"""Editorial sentence sets for the bundled Listen and Repeat catalog."""
# ruff: noqa: E501

from __future__ import annotations

LISTEN_REPEAT_SENTENCES: dict[str, tuple[str, ...]] = {
    "library orientation": (
        "The library opens at eight each morning.",
        "Return borrowed laptops to the technology desk.",
        "Quiet study rooms are located on the second floor.",
        "You may reserve a group table through the library website.",
        "Food is allowed in the lobby, but drinks must have secure lids.",
        "If a book is unavailable, ask a librarian to request it from another campus.",
        "Before leaving the building, scan every borrowed item at the self-service machine near the exit.",
    ),
    "biology laboratory": (
        "Safety goggles are stored by the door.",
        "Label each sample before beginning the experiment.",
        "Place used glass slides in the marked container.",
        "Your lab partner will record the temperature every two minutes.",
        "Wash your hands thoroughly after working with the bacterial cultures.",
        "If any liquid spills, notify the instructor instead of cleaning it alone.",
        "Once the final measurement has been recorded, turn off the microscope light and cover the instrument.",
    ),
    "campus shuttle": (
        "The next shuttle leaves at ten fifteen.",
        "Show the driver your university identification card.",
        "The eastbound bus stops beside the science building.",
        "Large bicycles must be secured on the rack at the front.",
        "During evening service, the shuttle follows a shorter route through campus.",
        "If every seat is occupied, wait behind the yellow line for the following bus.",
        "Because road construction has closed College Avenue, today's departures may arrive several minutes behind schedule.",
    ),
    "student health center": (
        "The clinic accepts walk-ins until four o'clock.",
        "Bring your insurance card to every appointment.",
        "Prescription refills can be requested through the patient portal.",
        "A nurse will call your name when an examination room is ready.",
        "Students with fever should wear a mask while waiting in the lobby.",
        "For urgent concerns after closing time, contact the advice line printed on this card.",
        "If you need to cancel tomorrow's appointment, use the online form before the center closes today.",
    ),
    "art exhibition": (
        "The new exhibition opens on Friday evening.",
        "Leave backpacks in the lockers beside reception.",
        "Photography is permitted unless a red symbol appears nearby.",
        "The curator's talk will begin in the central gallery at noon.",
        "Several sculptures are fragile, so remain behind the floor markings.",
        "Visitors who want an audio guide can borrow headphones at the information counter.",
        "After viewing the final room, write your comments on a card and place it in the wooden box.",
    ),
    "career workshop": (
        "Today's workshop focuses on internship interviews.",
        "Place a copy of your résumé on the table.",
        "Career advisers will review cover letters after the presentation.",
        "Pair with someone who works in a different academic field.",
        "During the practice interview, answer each question in under two minutes.",
        "Students seeking private feedback may book a separate appointment for next week.",
        "When the mock interview ends, exchange notes with your partner before completing the reflection form.",
    ),
    "astronomy club": (
        "Tonight we will observe Jupiter and Mars.",
        "Meet beside the observatory shortly after sunset.",
        "Warm clothing is recommended because the dome remains open.",
        "Adjust the telescope only after a club officer gives permission.",
        "Cloudy weather may require us to replace observing with an indoor demonstration.",
        "To protect your night vision, cover bright phone screens with a red filter.",
        "Members who photograph the planets should upload their clearest images to the shared folder by Monday.",
    ),
    "recycling program": (
        "Blue containers are reserved for paper products.",
        "Rinse food jars before placing them in bins.",
        "Electronic waste is collected behind the student union on Wednesdays.",
        "Remove plastic wrapping from cardboard boxes before recycling them.",
        "The program awards points to residence halls that reduce landfill waste.",
        "Students can volunteer to weigh recycled materials at the end of each month.",
        "When you are uncertain about an item, check the illustrated guide rather than placing it in the wrong container.",
    ),
    "language exchange": (
        "Conversation tables meet every Thursday after class.",
        "Choose a name tag that shows your target language.",
        "Partners switch languages halfway through each thirty-minute session.",
        "Prepare one question about food, travel, or family traditions.",
        "Correct major misunderstandings, but allow your partner time to finish speaking.",
        "Anyone without a partner should speak to the coordinator near the whiteboard.",
        "At the end of the exchange, suggest one useful expression that your partner can practice before next week.",
    ),
    "music rehearsal": (
        "The orchestra will rehearse in Hall B.",
        "Tune your instrument before the conductor arrives.",
        "Percussion players should collect their equipment from the storage room.",
        "We will practice the final movement before returning to the opening.",
        "Mark any difficult rhythm in pencil so the score can be reused.",
        "If you cannot attend Saturday's concert, inform the section leader before tomorrow afternoon.",
        "After the full rehearsal, brass musicians will remain for ten minutes to review the closing passage.",
    ),
    "research symposium": (
        "Registration begins outside the main auditorium.",
        "Poster presenters receive clips at the welcome desk.",
        "The keynote address examines new methods for coastal research.",
        "Questions will be collected after each fifteen-minute presentation.",
        "Coffee and light refreshments are available between the morning panels.",
        "Researchers needing technical support should arrive before their assigned session begins.",
        "To receive a participation certificate, scan the attendance code displayed after the final discussion.",
    ),
    "sports center": (
        "The swimming pool closes for maintenance tonight.",
        "Indoor courts can be reserved one day ahead.",
        "Store valuables in a locker rather than beside the equipment.",
        "Fitness classes require online registration during busy evening hours.",
        "Clean each exercise machine with the provided towel after using it.",
        "Anyone borrowing a basketball must return it to reception before the center closes.",
        "If the emergency alarm sounds, leave through the nearest marked exit without returning to the changing room.",
    ),
    "museum visit": (
        "Our museum tour begins in the west wing.",
        "Keep your admission sticker visible during the visit.",
        "The ancient pottery collection is displayed beyond the marble staircase.",
        "Sketching is welcome, although pens are prohibited near original objects.",
        "The group will spend twenty minutes exploring the interactive map exhibit.",
        "Please save detailed questions until the guide pauses at the discussion area.",
        "Before boarding the return bus, count the students in your group and report any absence to the instructor.",
    ),
    "volunteer fair": (
        "More than forty organizations are recruiting volunteers today.",
        "Pick up an information booklet near the entrance.",
        "Environmental groups have tables along the windows on your left.",
        "Ask each organization how many hours its projects usually require.",
        "The sign-up area becomes crowded immediately after the afternoon presentation.",
        "Students interested in weekend projects should mark their availability on the yellow form.",
        "Before making a commitment, confirm whether transportation and training are included in the volunteer program.",
    ),
    "housing office": (
        "Housing applications open early next month.",
        "Take a numbered ticket before joining the line.",
        "Room-change requests require signatures from both current roommates.",
        "A housing adviser can explain the difference between meal plans.",
        "Submit maintenance photographs through the residence portal rather than by email.",
        "Students leaving campus midyear must schedule a room inspection with their hall manager.",
        "If your financial aid is still pending, ask the office to note this before the payment deadline.",
    ),
    "computer laboratory": (
        "Temporary passwords expire after the first login.",
        "Save course files in your university cloud folder.",
        "The color printer is available only for approved class projects.",
        "Report damaged keyboards using the label attached to each workstation.",
        "Large software downloads should be completed outside the busiest laboratory hours.",
        "If a computer freezes, record its station number before asking the technician for help.",
        "When your work is finished, sign out of every account and remove documents from the printer tray.",
    ),
    "field trip": (
        "The field trip bus departs at seven thirty.",
        "Wear sturdy shoes suitable for uneven ground.",
        "Lunch will be provided at the environmental research station.",
        "Each team should carry one notebook and a water-quality sensor.",
        "Stay within sight of the marked trail while collecting plant observations.",
        "If heavy rain begins, return directly to the shelter beside the parking area.",
        "Before we leave the site, compare your measurements with another team and explain any major difference.",
    ),
    "student newspaper": (
        "The editorial meeting starts at six tonight.",
        "Send article proposals to the section editor.",
        "Campus photographs must include the photographer's full name.",
        "Reporters should verify quotations before submitting their final drafts.",
        "This week's front page will focus on changes to public transportation.",
        "Writers covering the election must review the newspaper's impartiality guidelines in advance.",
        "After an article is edited, read the revised version carefully and respond to every question in the margin.",
    ),
    "theater production": (
        "Auditions will take place on the main stage.",
        "Prepare a short scene from any modern play.",
        "Costume measurements begin after the cast list is announced.",
        "Actors must check the rehearsal schedule before leaving each evening.",
        "The lighting crew will test the final scene without performers tomorrow.",
        "Because the lobby is being painted, everyone should enter through the backstage door.",
        "During technical rehearsal, remain silent near the control booth so the crew can hear all cues clearly.",
    ),
    "study group": (
        "Our study group meets beside the economics office.",
        "Bring your notes from the last three lectures.",
        "Maya will summarize the chapter on international trade first.",
        "We should spend most of our time solving practice problems.",
        "Write uncertain answers on the board so everyone can discuss them.",
        "Before choosing the next meeting time, check the date of our midterm examination.",
        "If the library room becomes unavailable, the group will move to the café across from the lecture hall.",
    ),
    "campus garden": (
        "The herb beds need water this afternoon.",
        "Garden tools are kept inside the green shed.",
        "New volunteers will learn how to identify invasive plants.",
        "Place ripe tomatoes in shallow boxes to prevent bruising.",
        "A portion of today's harvest will go to the neighborhood food pantry.",
        "Anyone using compost should close the wooden cover to keep animals away.",
        "After we finish planting the winter vegetables, record each variety on the map attached to the shed wall.",
    ),
    "photography course": (
        "Tomorrow's class meets near the river bridge.",
        "Charge both camera batteries before the outdoor session.",
        "Use manual focus when photographing objects through glass.",
        "The instructor will demonstrate portrait lighting in small groups.",
        "Select three images that show different approaches to depth and distance.",
        "Students borrowing lenses must inspect them for damage before leaving the equipment room.",
        "For the final critique, submit unedited files alongside the versions whose color and contrast you adjusted.",
    ),
    "history archive": (
        "The archive closes earlier on Fridays.",
        "Pencils are provided inside the reading room.",
        "Request manuscript boxes by completing a digital call slip.",
        "Keep documents flat on the foam supports while reading them.",
        "Personal cameras may be used after an archivist checks the material's restrictions.",
        "Researchers must preserve the existing order of every folder they examine.",
        "When citing an archived letter, include the collection name, box number, folder number, and document date.",
    ),
    "engineering showcase": (
        "Student prototypes are displayed throughout the atrium.",
        "Robotics demonstrations begin every half hour.",
        "Wear protective glasses near the laser-cutting exhibit.",
        "Judges will evaluate both technical design and practical usefulness.",
        "The solar vehicle team will answer questions beside the south entrance.",
        "Presenters should test every electrical connection before visitors enter the demonstration area.",
        "If your prototype requires additional power, contact the facilities coordinator instead of using an unmarked outlet.",
    ),
    "international festival": (
        "The international festival fills the central courtyard today.",
        "Food tickets are sold beside the fountain.",
        "Dance performances alternate between the indoor and outdoor stages.",
        "Check ingredient cards carefully if you have any food allergies.",
        "Student groups will teach traditional games throughout the early afternoon.",
        "Visitors may collect a schedule translated into five languages at the welcome tent.",
        "When the closing parade reaches the library, follow the marked path so emergency routes remain clear.",
    ),
    "tutoring center": (
        "Free tutoring is available from Monday through Saturday.",
        "Check in using the tablet near reception.",
        "Writing appointments last longer than drop-in mathematics sessions.",
        "Bring the assignment instructions as well as your attempted solution.",
        "Tutors can explain difficult concepts, but they cannot complete graded work.",
        "Students who miss two appointments must speak with the coordinator before booking again.",
        "At the end of your session, identify one skill to practice independently before meeting the tutor again.",
    ),
    "book discussion": (
        "This month's novel is set in coastal Maine.",
        "The discussion begins with the author's use of setting.",
        "Choose one passage that changed your opinion of a character.",
        "Avoid revealing the ending until everyone has finished the opening activity.",
        "Small groups will compare the narrator's claims with evidence from the story.",
        "Readers who disliked the novel should explain which specific choices weakened it.",
        "Before voting on next month's title, consider whether each suggested book is available in an affordable edition.",
    ),
    "science lecture": (
        "Tonight's lecture explores deep-sea ecosystems.",
        "Seats in the front rows are reserved for classes.",
        "The speaker will show video recorded by an underwater robot.",
        "Hold questions until the moderator opens the final discussion period.",
        "A transcript of the lecture will appear on the department website tomorrow.",
        "Anyone seeking course credit must submit a short response by Friday afternoon.",
        "Because the presentation includes rapidly flashing images, sensitive viewers may request an alternate recording from the department.",
    ),
    "film screening": (
        "The documentary screening begins promptly at seven.",
        "Silence mobile phones before entering the theater.",
        "Late arrivals should use the doors at the rear.",
        "The director will join a live video discussion after the film.",
        "Free tickets remain valid only until fifteen minutes before showtime.",
        "Audience members may submit questions by scanning the code printed on the program.",
        "When the credits end, remain seated while staff prepare the microphones for the question-and-answer session.",
    ),
    "community survey": (
        "The community survey takes about twelve minutes.",
        "Participation is voluntary and answers remain anonymous.",
        "Use the paper form if the online page fails to load.",
        "Survey assistants will visit residence halls throughout the coming week.",
        "Questions ask about transportation, public spaces, and access to local services.",
        "Participants may skip any item that makes them uncomfortable without giving a reason.",
        "After collecting the responses, the research team will publish a summary for students and neighborhood residents.",
    ),
}
