"""Parse answers from a filled-in worksheet Markdown file.

The parser extracts answers using regex patterns that match the template
format generated by `renderer.py`. Lenient by design: handles extra
whitespace, mixed case, and missing answers.
"""

from __future__ import annotations

import re


def parse_fill_blanks(text: str) -> list[str]:
    """Extract answers from 'Your answer: ____' lines."""
    pattern = r"\*\*Your answer:\*\*\s*(.+)"
    matches = re.findall(pattern, text)
    return [m.strip().upper() for m in matches]


def parse_error_corrections(text: str) -> list[dict[str, str]]:
    """Extract error correction answers.

    Returns a list of {"correct": ..., "rule": ...} dicts.
    """
    corrects = re.findall(r"\*\*Correct:\*\*\s*(.+)", text)
    rules = re.findall(r"\*\*Rule:\*\*\s*(.+)", text)
    result: list[dict[str, str]] = []
    for i, c in enumerate(corrects):
        rule = rules[i].strip() if i < len(rules) else ""
        result.append({"correct": c.strip(), "rule": rule})
    return result


def parse_sentence_transforms(text: str) -> list[str]:
    """Extract sentence transformation answers."""
    pattern = r"Your version:\s*(.+)"
    matches = re.findall(pattern, text)
    return [m.strip() for m in matches]


def parse_collocation_matches(text: str) -> list[str]:
    """Extract collocation match answers from table rows.

    Looks for rows like: | word | ... | where the user fills in a letter.
    Returns a list of letter answers.
    """
    # Match table rows that have a word in the first cell and options in the second.
    # The user writes their answer letter somewhere in the row.
    rows = re.findall(r"\|\s*\w[\w\s-]*\s*\|\s*([A-Da-d])[\)\.]?\s*", text)
    return [r.upper() for r in rows]


def parse_worksheet_answers(text: str) -> dict[str, list]:
    """Parse all answer types from a filled-in worksheet file.

    Returns a dict keyed by exercise type, each containing a list of answers.
    """
    return {
        "fill_blanks": parse_fill_blanks(text),
        "error_correction": parse_error_corrections(text),
        "sentence_transform": parse_sentence_transforms(text),
        "collocation_match": parse_collocation_matches(text),
    }


def normalize_letter(answer: str) -> int | None:
    """Convert a letter answer (A/B/C/D) to an index (0/1/2/3).

    Returns None if the answer is not a valid letter.
    """
    answer = answer.strip().upper()
    if len(answer) == 1 and answer in "ABCD":
        return ord(answer) - ord("A")
    # Also accept numeric answers.
    if answer.isdigit() and 0 <= int(answer) <= 3:
        return int(answer)
    return None
